name: flutter_exercise
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  drift: 1.3.0
  sqlite3_flutter_libs: 0.5.3
  path_provider: 2.0.8
  path: 1.8.0

  flutter_secure_storage: 5.0.2

  copy_with_extension: 4.0.0

  flutter_riverpod: 2.0.0-dev.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  drift_dev: 1.3.0

  copy_with_extension_gen: 4.0.0

  build_runner: 2.1.7

  flutter_lints: 1.0.4

flutter:
  uses-material-design: true